[package]
name = "xml-pretty"
version = "0.1.0"
edition = "2021"
description = "XML prettifer binary"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/bbqsrc/xml-pretty"

[dependencies]
anyhow = "1.0.57"
gumdrop = "0.8.1"
xmlem = { git = "https://github.com/bbqsrc/xmlem" }
